In [123]:
%load_ext autoreload
%autoreload 2

import os
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error

if 'cachai' not in os.listdir('.'):
    os.chdir('../')
    
import cachai.utils.constants as C
import cachai.utils.types as T  
from cachai.utils.metrics import evaluate, evaluate_group
from cachai.simulators.ttl_simulator import TTLSimulator
from cachai.strategies.debugger_strategy import DebuggerStrategy
from cachai.strategies.heuristics_strategy import ConstantStrategy
from config.debugger_config import debugger_experiments
from config.heuristics_config import constant_experiments

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [124]:
from typing import List


def strategy_from_config(strategy_config: T.StrategyConfig) -> None:
    params = strategy_config.params
    if strategy_config.type == 'DebuggerStrategy':
        return DebuggerStrategy()
    elif strategy_config.type == 'ConstantStrategy':
        return ConstantStrategy(params)
    else:
        raise ValueError(f'Unknown strategy type: {strategy_config.type}')


def simulator_from_config(simulator_config: T.SimulatorConfig) -> None:
    if simulator_config.type == 'TTLSimulator':
        return TTLSimulator()
    else:
        raise ValueError(f'Unknown simulator type: {simulator_config.type}')


def run_experiments(experiments: List[T.ExperimentConfig]) -> pd.DataFrame:
    df = []
    for experiment in experiments:
        experiment_name = experiment.experiment_name
        experiment_config = experiment.experiment_config
        simulator = simulator_from_config(experiment.simulator_config)
        strategy = strategy_from_config(experiment.strategy_config)

        for i in range(experiment_config.iterations):
            X, y_true = simulator.generate()

            info = {C.Y_TRUE: y_true if experiment_config.debug else None}
            y_pred = strategy.predict(X, info)
            observation_time, observation_type, hits = simulator.feedback(y_true, y_pred)
            strategy.observe(observation_time, observation_type, hits, y_pred, info)
            df.append([
                experiment_name, strategy.NAME, i, observation_type,
                observation_time, y_pred[0], y_true[0], hits
            ])
    return pd.DataFrame(df, columns=[
        C.EXPERIMENT_NAME, C.STRATEGY_NAME, C.ITERATION, C.OBSERVATION_TYPE,
        C.OBSERVATION_TIME, C.Y_PRED, C.Y_TRUE, C.HITS
    ])

In [125]:
df = run_experiments([
    *debugger_experiments,
    *constant_experiments
])
df.head(10)

,experiment_name,strategy_name,iteration,observation_type,observation_time,y_pred,y_true,hits,mae
0,Debugger Test,DebuggerStrategy,0,valid_ttl,37,37.159731,37.159731,36,0.0
1,Debugger Test,DebuggerStrategy,1,valid_ttl,354,354.359373,354.359373,353,0.0
2,Debugger Test,DebuggerStrategy,2,valid_ttl,59,59.742850,59.742850,58,0.0
3,Debugger Test,DebuggerStrategy,3,valid_ttl,204,204.562823,204.562823,203,0.0
4,Debugger Test,DebuggerStrategy,4,valid_ttl,208,208.238231,208.238231,207,0.0
5,Debugger Test,DebuggerStrategy,5,valid_ttl,208,208.552051,208.552051,207,0.0
6,Debugger Test,DebuggerStrategy,6,valid_ttl,399,399.048110,399.048110,398,0.0
7,Debugger Test,DebuggerStrategy,7,valid_ttl,447,447.684140,447.684140,446,0.0
8,Debugger Test,DebuggerStrategy,8,valid_ttl,373,373.050319,373.050319,372,0.0
9,Debugger Test,DebuggerStrategy,9,valid_ttl,52,52.988639,52.988639,51,0.0

In [126]:
evaluate_group(df)

,,,rmse,mae,mabe,msbe,hit_rate,miss_rate,precision,accuracy,recall,false_positive_rate,f1_score,hits_total,hits_mean,len
experiment_name,strategy_name,,,,,,,,,,,,,,,
Constant 0,ConstantStrategy,0,260.730822,215.971020,215.971020,67980.561544,0.000,1.000,0.0,0.0,0.0,0.0,0,0,0.000,1000
Constant 100,ConstantStrategy,0,185.063385,148.840570,148.840570,34248.456377,0.339,0.661,0.0,0.0,0.0,1.0,0,81909,81.909,1000
Constant 150,ConstantStrategy,0,158.172903,132.281126,132.281126,25018.667154,0.353,0.647,0.0,0.0,0.0,1.0,0,113513,113.513,1000
Constant 200,ConstantStrategy,0,144.626315,118.261850,118.261850,20916.770911,0.496,0.504,0.0,0.0,0.0,1.0,0,147305,147.305,1000
Constant 250,ConstantStrategy,0,148.972233,133.316671,133.316671,22192.726349,0.698,0.302,0.0,0.0,0.0,1.0,0,161288,161.288,1000
Constant 300,ConstantStrategy,0,166.240169,149.471202,149.471202,27635.793681,0.657,0.343,0.0,0.0,0.0,1.0,0,183893,183.893,1000
Constant 350,ConstantStrategy,0,197.199291,167.086508,167.086508,38887.560390,0.680,0.320,0.0,0.0,0.0,1.0,0,198442,198.442,1000
Constant 400,ConstantStrategy,0,232.225776,190.152528,190.152528,53928.810865,0.836,0.164,0.0,0.0,0.0,1.0,0,212197,212.197,1000
Constant 450,ConstantStrategy,0,281.976554,243.206640,243.206640,79510.776991,0.987,0.013,0.0,0.0,0.0,1.0,0,205408,205.408,1000
Constant 50,ConstantStrategy,0,222.560098,169.953159,169.953159,49532.997443,0.158,0.842,0.0,0.0,0.0,1.0,0,48250,48.250,1000
Debugger Test,DebuggerStrategy,0,0.000000,0.000000,0.000000,0.000000,0.000,1.000,0.0,1.0,0.0,0.0,0,215197,215.197,1000