In [12]:
%load_ext autoreload
%autoreload 2

import os
import numpy as np
import pandas as pd

if 'cachai' not in os.listdir('.'):
    os.chdir('../')
    
import cachai.utils.constants as C
from cachai.utils.metrics import evaluate, evaluate_group
from cachai.strategies.debugger_strategy import DebuggerStrategy

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
from sklearn.metrics import mean_absolute_error


class TTLSimulator:

    def __init__(self, iterations=1_000):
        self._iterations = iterations
        self._target_params = [
            (50, 5),
            (200, 10),
            (400, 30),
        ]
        # means = np.linspace(10, 500, 10).astype(int)
        # std = np.arange(1, len(means) + 1)**2
        # self._target_params = np.array([means, std]).T

    def update_target_params(self, progress):
        target_params = []
        for param in self._target_params:
            mean = float(
                round(param[0]*np.sin(progress*2*np.pi/2)/(param[0]/2) + param[0], 2)
            )
            std = param[1]
            target_params.append((mean, std))
        self._target_params = target_params

    def feedback(self, y_true, y_pred):
        observation_time = int(min(y_true, y_pred)[0])
        hits = max(0, observation_time-1)
        observation_type = None
        if y_pred[0] < y_true[0]:
            observation_type = C.MISS
        elif y_pred[0] > y_true[0]:
            observation_type = C.STALE
        else:
            observation_type = C.VALID_TTL
        return observation_time, observation_type, hits

    def generate(self):
        # get target
        target_param_index = np.random.randint(0, len(self._target_params))
        target_params = self._target_params[target_param_index]
        y = np.random.normal(target_params[0], target_params[1], 1)

        # generate features from target
        num_features = 1
        correlation = 0.8
        cov_matrix = np.eye(num_features) * (1 - correlation) + np.ones((num_features, num_features)) * correlation
        features = np.random.multivariate_normal(np.ones(num_features) * y, cov_matrix)
        X = features.reshape(1, -1)
        # X = np.full((1, num_features), fill_value=target)
        return X, y

In [14]:
class Experiment():

    DF_COLUMNS = [
        C.EXPERIMENT_NAME, C.STRATEGY_NAME, C.ITERATION, C.OBSERVATION_TYPE,
        C.OBSERVATION_TIME, C.Y_PRED, C.Y_TRUE, C.HITS, C.MAE
    ]

    def __init__(self, simulator, iterations=1_000):
        self._simulator = simulator
        self._iterations = iterations

    def run(self, experiments):
        df = []
        for experiment in experiments:
            experiment_name = experiment[C.EXPERIMENT_NAME]
            strategy = experiment[C.STRATEGY]
            debug = experiment[C.DEBUG]
            for i in range(self._iterations):
                X, y_true = self._simulator.generate()

                info = {C.Y_TRUE: y_true if debug else None}
                y_pred = strategy.predict(X, info)
                observation_time, observation_type, hits = self._simulator.feedback(y_true, y_pred)
                strategy.observe(observation_time, observation_type, hits, y_pred, info)

                mae = mean_absolute_error(y_true, y_pred)
                df.append([
                    experiment_name, strategy.NAME, i, observation_type,
                    observation_time, y_pred[0], y_true[0], hits, mae
                ])
        return pd.DataFrame(df, columns=Experiment.DF_COLUMNS)

In [15]:
simulator = TTLSimulator()
experiment = Experiment(simulator=simulator)
df = experiment.run([
    {
        C.EXPERIMENT_NAME: 'Debug experiment',
        C.STRATEGY: DebuggerStrategy(),
        C.DEBUG: True
    },
])
df.head(10)

,experiment_name,strategy_name,iteration,observation_type,observation_time,y_pred,y_true,hits,mae
0,Debug experiment,DebuggerStrategy,0,valid_ttl,49,49.491938,49.491938,48,0.0
1,Debug experiment,DebuggerStrategy,1,valid_ttl,196,196.036176,196.036176,195,0.0
2,Debug experiment,DebuggerStrategy,2,valid_ttl,195,195.337542,195.337542,194,0.0
3,Debug experiment,DebuggerStrategy,3,valid_ttl,44,44.228304,44.228304,43,0.0
4,Debug experiment,DebuggerStrategy,4,valid_ttl,45,45.326491,45.326491,44,0.0
5,Debug experiment,DebuggerStrategy,5,valid_ttl,47,47.808181,47.808181,46,0.0
6,Debug experiment,DebuggerStrategy,6,valid_ttl,382,382.345787,382.345787,381,0.0
7,Debug experiment,DebuggerStrategy,7,valid_ttl,56,56.331957,56.331957,55,0.0
8,Debug experiment,DebuggerStrategy,8,valid_ttl,407,407.450552,407.450552,406,0.0
9,Debug experiment,DebuggerStrategy,9,valid_ttl,60,60.282821,60.282821,59,0.0

In [16]:
evaluate_group(df)

,,,rmse,mae,mabe,msbe,hit_rate,miss_rate,precision,accuracy,recall,false_positive_rate,f1_score,hits_total,hits_mean,len
experiment_name,strategy_name,,,,,,,,,,,,,,,
Debug experiment,DebuggerStrategy,0,0.0,0.0,0.0,0.0,0.0,1.0,0,1.0,0,0,0,219493,219.493,1000