In [4]:
%load_ext autoreload
%autoreload 2

import os
import numpy as np
import pandas as pd
import plotly.express as px

if 'cachai' not in os.listdir('.'):
    os.chdir('../')
    
import cachai.utils.types as T  
import cachai.utils.models as M
import cachai.utils.constants as C
from cachai.utils.metrics import evaluate, evaluate_group
from cachai.simulators.ttl_simulator import TTLSimulator
from cachai.strategies.debugger_strategy import DebuggerStrategy
from cachai.strategies.heuristics_strategy import ConstantStrategy
from config.debugger_config import debugger_experiments
from config.heuristics_config import constant_experiments

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
from typing import List


def strategy_from_config(strategy_config: M.StrategyConfig) -> None:
    params = strategy_config.params
    if strategy_config.type == DebuggerStrategy.NAME:
        return DebuggerStrategy()
    elif strategy_config.type == ConstantStrategy.NAME:
        return ConstantStrategy(params)
    else:
        raise ValueError(f'Unknown strategy type: {strategy_config.type}')


def simulator_from_config(simulator_config: M.SimulatorConfig) -> None:
    if simulator_config.type == 'TTLSimulator':
        return TTLSimulator()
    else:
        raise ValueError(f'Unknown simulator type: {simulator_config.type}')


def run_experiments(experiments: List[M.ExperimentConfig]) -> pd.DataFrame:
    df = []
    for experiment in experiments:
        experiment_name = experiment.experiment_name
        experiment_config = experiment.experiment_config
        simulator = simulator_from_config(experiment.simulator_config)
        strategy = strategy_from_config(experiment.strategy_config)

        for i in range(experiment_config.iterations):
            X, y_true = simulator.generate()

            info = {C.Y_TRUE: y_true if experiment_config.debug else None}
            y_pred = strategy.predict(X, info)
            observation_time, observation_type, hits = simulator.feedback(y_true, y_pred)
            strategy.observe(observation_time, observation_type, hits, y_pred, info)

            df.append([
                experiment_name, strategy.NAME, i, observation_type,
                observation_time, y_pred[0], y_true[0], hits
            ])
    return pd.DataFrame(df, columns=[
        C.EXPERIMENT_NAME, C.STRATEGY_NAME, C.ITERATION, C.OBSERVATION_TYPE,
        C.OBSERVATION_TIME, C.Y_PRED, C.Y_TRUE, C.HITS
    ])

In [6]:
df = run_experiments([
    *debugger_experiments,
    *constant_experiments
])
df.head(10)

,experiment_name,strategy_name,iteration,observation_type,observation_time,y_pred,y_true,hits
0,Debugger Test,DebuggerStrategy,0,valid_ttl,50,50.935761,50.935761,49
1,Debugger Test,DebuggerStrategy,1,valid_ttl,204,204.814203,204.814203,203
2,Debugger Test,DebuggerStrategy,2,valid_ttl,445,445.783388,445.783388,444
3,Debugger Test,DebuggerStrategy,3,valid_ttl,200,200.918358,200.918358,199
4,Debugger Test,DebuggerStrategy,4,valid_ttl,203,203.595369,203.595369,202
5,Debugger Test,DebuggerStrategy,5,valid_ttl,423,423.283873,423.283873,422
6,Debugger Test,DebuggerStrategy,6,valid_ttl,56,56.445414,56.445414,55
7,Debugger Test,DebuggerStrategy,7,valid_ttl,59,59.836776,59.836776,58
8,Debugger Test,DebuggerStrategy,8,valid_ttl,46,46.303763,46.303763,45
9,Debugger Test,DebuggerStrategy,9,valid_ttl,326,326.903973,326.903973,325

In [7]:
metrics = evaluate_group(df)
metrics

,,,rmse,mae,mabe,msbe,hit_rate,miss_rate,precision,accuracy,recall,false_positive_rate,f1_score,hits_total,hits_mean,len
experiment_name,strategy_name,,,,,,,,,,,,,,,
Constant 0,ConstantStrategy,0,257.084807,215.124152,215.124152,66092.597769,0.000,1.000,0.0,0.0,0.0,0.0,0,0,0.000,1000
Constant 100,ConstantStrategy,0,185.228273,149.543696,149.543696,34309.513054,0.335,0.665,0.0,0.0,0.0,1.0,0,82113,82.113,1000
Constant 150,ConstantStrategy,0,161.384778,136.516099,136.516099,26045.046463,0.349,0.651,0.0,0.0,0.0,1.0,0,113876,113.876,1000
Constant 200,ConstantStrategy,0,148.741989,123.475575,123.475575,22124.179267,0.477,0.523,0.0,0.0,0.0,1.0,0,149586,149.586,1000
Constant 250,ConstantStrategy,0,148.799557,133.889424,133.889424,22141.308172,0.670,0.330,0.0,0.0,0.0,1.0,0,164899,164.899,1000
Constant 300,ConstantStrategy,0,165.295925,148.322475,148.322475,27322.742738,0.678,0.322,0.0,0.0,0.0,1.0,0,182175,182.175,1000
Constant 350,ConstantStrategy,0,198.104451,169.047098,169.047098,39245.373585,0.696,0.304,0.0,0.0,0.0,1.0,0,195513,195.513,1000
Constant 400,ConstantStrategy,0,233.255633,191.301001,191.301001,54408.190527,0.856,0.144,0.0,0.0,0.0,1.0,0,211235,211.235,1000
Constant 450,ConstantStrategy,0,279.710203,239.598809,239.598809,78237.797497,0.988,0.012,0.0,0.0,0.0,1.0,0,209029,209.029,1000
Constant 50,ConstantStrategy,0,224.988907,171.364219,171.364219,50620.008401,0.165,0.835,0.0,0.0,0.0,1.0,0,48234,48.234,1000
Debugger Test,DebuggerStrategy,0,0.000000,0.000000,0.000000,0.000000,0.000,1.000,0.0,1.0,0.0,0.0,0,208020,208.020,1000

In [8]:
metrics_df = metrics.reset_index()
px.bar(
    metrics_df,
    x=C.STRATEGY_NAME,
    y=[C.RMSE],
    color=C.EXPERIMENT_NAME,
    barmode='group'
)