In [7]:
%load_ext autoreload
%autoreload 2

import os
import numpy as np
import pandas as pd
import plotly.express as px

if 'cachai' not in os.listdir('.'):
    os.chdir('../')
    
import cachai.utils.types as T  
import cachai.utils.models as M
import cachai.utils.constants as C
from cachai.utils.metrics import evaluate, evaluate_group
from cachai.simulators.ttl_simulator import TTLSimulator
from cachai.strategies.debugger_strategy import DebuggerStrategy
from cachai.strategies.heuristics_strategy import ConstantStrategy
from config.debugger_config import debugger_experiments
from config.heuristics_config import constant_experiments

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
from typing import List


def strategy_from_config(strategy_config: M.StrategyConfig) -> None:
    params = strategy_config.params
    if strategy_config.type == 'DebuggerStrategy':
        return DebuggerStrategy()
    elif strategy_config.type == 'ConstantStrategy':
        return ConstantStrategy(params)
    else:
        raise ValueError(f'Unknown strategy type: {strategy_config.type}')


def simulator_from_config(simulator_config: M.SimulatorConfig) -> None:
    if simulator_config.type == 'TTLSimulator':
        return TTLSimulator()
    else:
        raise ValueError(f'Unknown simulator type: {simulator_config.type}')


def run_experiments(experiments: List[M.ExperimentConfig]) -> pd.DataFrame:
    df = []
    for experiment in experiments:
        experiment_name = experiment.experiment_name
        experiment_config = experiment.experiment_config
        simulator = simulator_from_config(experiment.simulator_config)
        strategy = strategy_from_config(experiment.strategy_config)

        for i in range(experiment_config.iterations):
            X, y_true = simulator.generate()

            info = {C.Y_TRUE: y_true if experiment_config.debug else None}
            y_pred = strategy.predict(X, info)
            observation_time, observation_type, hits = simulator.feedback(y_true, y_pred)
            strategy.observe(observation_time, observation_type, hits, y_pred, info)

            df.append([
                experiment_name, strategy.NAME, i, observation_type,
                observation_time, y_pred[0], y_true[0], hits
            ])
    return pd.DataFrame(df, columns=[
        C.EXPERIMENT_NAME, C.STRATEGY_NAME, C.ITERATION, C.OBSERVATION_TYPE,
        C.OBSERVATION_TIME, C.Y_PRED, C.Y_TRUE, C.HITS
    ])

AttributeError: module 'cachai.utils.types' has no attribute 'StrategyConfig'

In [14]:
df = run_experiments([
    *debugger_experiments,
    *constant_experiments
])
df.head(10)

,experiment_name,strategy_name,iteration,observation_type,observation_time,y_pred,y_true,hits
0,Debugger Test,DebuggerStrategy,0,valid_ttl,50,50.689511,50.689511,49
1,Debugger Test,DebuggerStrategy,1,valid_ttl,399,399.680584,399.680584,398
2,Debugger Test,DebuggerStrategy,2,valid_ttl,54,54.708968,54.708968,53
3,Debugger Test,DebuggerStrategy,3,valid_ttl,50,50.013861,50.013861,49
4,Debugger Test,DebuggerStrategy,4,valid_ttl,193,193.020543,193.020543,192
5,Debugger Test,DebuggerStrategy,5,valid_ttl,417,417.769948,417.769948,416
6,Debugger Test,DebuggerStrategy,6,valid_ttl,196,196.101827,196.101827,195
7,Debugger Test,DebuggerStrategy,7,valid_ttl,47,47.986244,47.986244,46
8,Debugger Test,DebuggerStrategy,8,valid_ttl,51,51.180212,51.180212,50
9,Debugger Test,DebuggerStrategy,9,valid_ttl,195,195.474724,195.474724,194

In [15]:
metrics = evaluate_group(df)
metrics

,,,rmse,mae,mabe,msbe,hit_rate,miss_rate,precision,accuracy,recall,false_positive_rate,f1_score,hits_total,hits_mean,len
experiment_name,strategy_name,,,,,,,,,,,,,,,
Constant 0,ConstantStrategy,0,259.669926,214.953351,214.953351,67428.470469,0.000,1.000,0.0,0.0,0.0,0.0,0,0,0.000,1000
Constant 100,ConstantStrategy,0,179.762367,144.457221,144.457221,32314.508624,0.342,0.658,0.0,0.0,0.0,1.0,0,81679,81.679,1000
Constant 150,ConstantStrategy,0,158.719113,133.526990,133.526990,25191.756957,0.357,0.643,0.0,0.0,0.0,1.0,0,113125,113.125,1000
Constant 200,ConstantStrategy,0,147.389715,122.508130,122.508130,21723.728144,0.510,0.490,0.0,0.0,0.0,1.0,0,146223,146.223,1000
Constant 250,ConstantStrategy,0,147.321198,131.732867,131.732867,21703.535368,0.691,0.309,0.0,0.0,0.0,1.0,0,162263,162.263,1000
Constant 300,ConstantStrategy,0,163.768690,147.104339,147.104339,26820.183878,0.666,0.334,0.0,0.0,0.0,1.0,0,184868,184.868,1000
Constant 350,ConstantStrategy,0,198.947427,168.912419,168.912419,39580.078636,0.689,0.311,0.0,0.0,0.0,1.0,0,196053,196.053,1000
Constant 400,ConstantStrategy,0,228.537230,185.017046,185.017046,52229.265631,0.819,0.181,0.0,0.0,0.0,1.0,0,218011,218.011,1000
Constant 450,ConstantStrategy,0,276.101532,236.885483,236.885483,76232.055746,0.986,0.014,0.0,0.0,0.0,1.0,0,211784,211.784,1000
Constant 50,ConstantStrategy,0,222.102730,169.833489,169.833489,49329.622844,0.152,0.848,0.0,0.0,0.0,1.0,0,48293,48.293,1000
Debugger Test,DebuggerStrategy,0,0.000000,0.000000,0.000000,0.000000,0.000,1.000,0.0,1.0,0.0,0.0,0,220281,220.281,1000

In [16]:
px.bar(
    metrics.reset_index(),
    x=C.STRATEGY_NAME,
    y=C.HITS_TOTAL,
    color=C.EXPERIMENT_NAME,
    barmode='group'
)