In [8]:
%load_ext autoreload
%autoreload 2

import os
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error

if 'cachai' not in os.listdir('.'):
    os.chdir('../')
    
import cachai.utils.constants as C
import cachai.utils.types as T  
from cachai.utils.metrics import evaluate, evaluate_group
from cachai.simulators.ttl_simulator import TTLSimulator
from cachai.strategies.debugger_strategy import DebuggerStrategy
from cachai.strategies.heuristics_strategy import ConstantStrategy

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
from typing import List


def strategy_from_config(strategy_config: T.StrategyConfig) -> None:
    if strategy_config.type == 'DebuggerStrategy':
        return DebuggerStrategy()
    elif strategy_config.type == 'ConstantStrategy':
        return ConstantStrategy()
    else:
        raise ValueError(f'Unknown strategy type: {strategy_config.type}')


def simulator_from_config(simulator_config: T.SimulatorConfig) -> None:
    if simulator_config.type == 'TTLSimulator':
        return TTLSimulator()
    else:
        raise ValueError(f'Unknown simulator type: {simulator_config.type}')


def run_experiments(experiments: List[T.ExperimentConfig]) -> pd.DataFrame:
    df = []
    for experiment in experiments:
        experiment_name = experiment.experiment_name
        experiment_config = experiment.experiment_config
        simulator = simulator_from_config(experiment.simulator_config)
        strategy = strategy_from_config(experiment.strategy_config)

        for i in range(experiment_config.iterations):
            X, y_true = simulator.generate()

            info = {C.Y_TRUE: y_true if experiment_config.debug else None}
            y_pred = strategy.predict(X, info)
            observation_time, observation_type, hits = simulator.feedback(y_true, y_pred)
            strategy.observe(observation_time, observation_type, hits, y_pred, info)

            mae = mean_absolute_error(y_true, y_pred)
            df.append([
                experiment_name, strategy.NAME, i, observation_type,
                observation_time, y_pred[0], y_true[0], hits, mae
            ])
    return pd.DataFrame(df, columns=[
        C.EXPERIMENT_NAME, C.STRATEGY_NAME, C.ITERATION, C.OBSERVATION_TYPE,
        C.OBSERVATION_TIME, C.Y_PRED, C.Y_TRUE, C.HITS, C.MAE
    ])

In [11]:
df = run_experiments([
    T.Experiment(
        experiment_name='Debugger Test',
        experiment_config=T.ExperimentConfig(
            iterations=1_000,
            debug=True
        ),
        simulator_config=T.SimulatorConfig(
            type='TTLSimulator'
        ),
        strategy_config=T.StrategyConfig(
            type='DebuggerStrategy'
        )
    )
])
df.head(10)

,experiment_name,strategy_name,iteration,observation_type,observation_time,y_pred,y_true,hits,mae
0,Debugger Test,DebuggerStrategy,0,valid_ttl,403,403.595360,403.595360,402,0.0
1,Debugger Test,DebuggerStrategy,1,valid_ttl,396,396.405580,396.405580,395,0.0
2,Debugger Test,DebuggerStrategy,2,valid_ttl,59,59.071657,59.071657,58,0.0
3,Debugger Test,DebuggerStrategy,3,valid_ttl,316,316.064143,316.064143,315,0.0
4,Debugger Test,DebuggerStrategy,4,valid_ttl,50,50.226685,50.226685,49,0.0
5,Debugger Test,DebuggerStrategy,5,valid_ttl,209,209.673859,209.673859,208,0.0
6,Debugger Test,DebuggerStrategy,6,valid_ttl,50,50.521072,50.521072,49,0.0
7,Debugger Test,DebuggerStrategy,7,valid_ttl,191,191.103456,191.103456,190,0.0
8,Debugger Test,DebuggerStrategy,8,valid_ttl,51,51.595939,51.595939,50,0.0
9,Debugger Test,DebuggerStrategy,9,valid_ttl,430,430.490903,430.490903,429,0.0

In [12]:
evaluate_group(df)

,,,rmse,mae,mabe,msbe,hit_rate,miss_rate,precision,accuracy,recall,false_positive_rate,f1_score,hits_total,hits_mean,len
experiment_name,strategy_name,,,,,,,,,,,,,,,
Debugger Test,DebuggerStrategy,0,0.0,0.0,0.0,0.0,0.0,1.0,0,1.0,0,0,0,204944,204.944,1000